# STRIPE LIVE ACCOUNT
#Stripe.api_key = "S27kWbmJvSItmxe9xl2XWS9OOqGJcjtE"
#STRIPE_PUBLIC_KEY = "pk_XeTF5KrqXMeSyyqApBF4q9qDzniMn"

# STRIPE TEST ACCOUNT
Stripe.api_key = "yX8LAOzSjtx7wtZOK2HQnKe2CU772oFm"
STRIPE_PUBLIC_KEY = "pk_GP95lUPyExWOy8e81qL5vIbwMH7G8"
