# Currently unused. Will be used once I better define our environments.

defaults: &defaults
  host: localhost
  port: 6379

development:
  <<: *defaultstest:
  <<: *defaults 

staging:
  <<: *defaults

production:
  <<: *defaults	
