# Currently unused. Will be used once I better define our environments.p

defaults: &defaults
  host: '127.0.0.1' #localhost
  port: 6379

development:
  <<: *defaults 

#"redis://redistogo:b78903562b573eca1f7245bfd29a8986@spadefish.redistogo.com:9247/"
staging:
  host: 'spadefish.redistogo.com'
  port: 9247
  password: 'b78903562b573eca1f7245bfd29a8986'
  thread_safe: true
	

#"redis://redistogo:b78903562b573eca1f7245bfd29a8986@spadefish.redistogo.com:9247/"
production:
  <<: *defaults 
  host: 'spadefish.redistogo.com'
  port: 9362
  password: '4c72d254881eb818aa62d5c02ca36128'
  thread_safe: true

