require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComplaintsController do

  # This should return the minimal set of attributes required to create a valid
  # Complaint. As you add validations to Complaint, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ComplaintsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all complaints as @complaints" do
      complaint = Complaint.create! valid_attributes
      get :index, {}, valid_session
      assigns(:complaints).should eq([complaint])
    end
  end

  describe "GET show" do
    it "assigns the requested complaint as @complaint" do
      complaint = Complaint.create! valid_attributes
      get :show, {:id => complaint.to_param}, valid_session
      assigns(:complaint).should eq(complaint)
    end
  end

  describe "GET new" do
    it "assigns a new complaint as @complaint" do
      get :new, {}, valid_session
      assigns(:complaint).should be_a_new(Complaint)
    end
  end

  describe "GET edit" do
    it "assigns the requested complaint as @complaint" do
      complaint = Complaint.create! valid_attributes
      get :edit, {:id => complaint.to_param}, valid_session
      assigns(:complaint).should eq(complaint)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Complaint" do
        expect {
          post :create, {:complaint => valid_attributes}, valid_session
        }.to change(Complaint, :count).by(1)
      end

      it "assigns a newly created complaint as @complaint" do
        post :create, {:complaint => valid_attributes}, valid_session
        assigns(:complaint).should be_a(Complaint)
        assigns(:complaint).should be_persisted
      end

      it "redirects to the created complaint" do
        post :create, {:complaint => valid_attributes}, valid_session
        response.should redirect_to(Complaint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved complaint as @complaint" do
        # Trigger the behavior that occurs when invalid params are submitted
        Complaint.any_instance.stub(:save).and_return(false)
        post :create, {:complaint => {}}, valid_session
        assigns(:complaint).should be_a_new(Complaint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Complaint.any_instance.stub(:save).and_return(false)
        post :create, {:complaint => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested complaint" do
        complaint = Complaint.create! valid_attributes
        # Assuming there are no other complaints in the database, this
        # specifies that the Complaint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Complaint.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => complaint.to_param, :complaint => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested complaint as @complaint" do
        complaint = Complaint.create! valid_attributes
        put :update, {:id => complaint.to_param, :complaint => valid_attributes}, valid_session
        assigns(:complaint).should eq(complaint)
      end

      it "redirects to the complaint" do
        complaint = Complaint.create! valid_attributes
        put :update, {:id => complaint.to_param, :complaint => valid_attributes}, valid_session
        response.should redirect_to(complaint)
      end
    end

    describe "with invalid params" do
      it "assigns the complaint as @complaint" do
        complaint = Complaint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Complaint.any_instance.stub(:save).and_return(false)
        put :update, {:id => complaint.to_param, :complaint => {}}, valid_session
        assigns(:complaint).should eq(complaint)
      end

      it "re-renders the 'edit' template" do
        complaint = Complaint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Complaint.any_instance.stub(:save).and_return(false)
        put :update, {:id => complaint.to_param, :complaint => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested complaint" do
      complaint = Complaint.create! valid_attributes
      expect {
        delete :destroy, {:id => complaint.to_param}, valid_session
      }.to change(Complaint, :count).by(-1)
    end

    it "redirects to the complaints list" do
      complaint = Complaint.create! valid_attributes
      delete :destroy, {:id => complaint.to_param}, valid_session
      response.should redirect_to(complaints_url)
    end
  end

end
